import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'



function Card(props) {
  return(
    <div class={styles.card}>
      <div class={styles.container}>
        <h4>Item: <b>{props.item}</b></h4>
        <p>Status: <b>{props.status}</b></p>
        <p> Description: {props.description} </p>
        <p>From {props.source} to {props.destination}</p>
        <p>Tracking Number: #{props.tracking_number}</p>
      </div>
    </div>
  )
}

export default function Home() {
  const [shipments, setShipments] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/shipment/list')
      .then(res => res.json())
      .then(data => {
        setShipments(data)
        setLoading(false)
      })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Shipment List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {loading ? <div>Loading...</div> : (
          <div>
            {shipments.map(shipment => (
              <Card
                key={shipment.id}
                item={shipment.item}
                status={shipment.status}
                source={shipment.source}
                destination={shipment.destination}
                tracking_number={shipment.tracking_number}
                description={shipment.description}
              />
            ))}
          </div>
        )}
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
